apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment_service
  template:
    metadata:
      labels:
        app: payment_service
    spec:
      containers:
      - name: payment_service
        image: tharindudecosta/payment_service:v1.0
        ports:
        - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: payment_service
spec:
  selector:
    app: payment_service
  ports:
  - protocol: TCP
    port: 4005
    targetPort: 4005